// Keeps src/react-native/bridge/version.ts in sync with package.json.
// Runs automatically via the npm "version" lifecycle (npm version patch/minor/...).
const fs = require('fs');
const path = require('path');

const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf8'));
const out = path.join(__dirname, '..', 'src', 'react-native', 'bridge', 'version.ts');
fs.writeFileSync(out, `// Generated by scripts/sync-version.js — do not edit by hand.
export const PIVOTX_VERSION = '${pkg.version}';
`);
console.log('version.ts →', pkg.version);
